export const stravaData = [
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "The Wave",
    "distance": 9629.2,
    "moving_time": 10314,
    "elapsed_time": 15957,
    "total_elevation_gain": 310.8,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 19285220251,
    "id_str": "19285220251",
    "start_date": "2026-07-12T11:18:20Z",
    "start_date_local": "2026-07-12T05:18:20Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 0,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a19285220251",
      "summary_polyline": "ug}`FlwvjTsAi@gAgAO_@Q}@EmBk@oDMyABBK_@SkB]qAEs@D[PKhC^fBGFHv@Q^sAQgCWiAY]{@c@BAkBQi@m@o@e@D]@q@BCGYDMEYHQd@KAcAF{@NWDe@PYp@e@T[ZE|@e@VB~CwB^g@@eAJa@v@u@HA|@u@FQb@e@p@Ul@qAbAqA|@s@Te@TYVw@CmALSVoACEKq@YKEQBa@N}@Vk@?k@PINa@r@a@zAUPWP?DFx@Ur@_@tA]LSTKNBPQDRIYLYV_@h@]TLPKv@@f@VT?HDD^tBfABVZf@VGRHPAHMNAXL^?JLVDBJJFb@WPi@JG?QD?FObA[f@]r@Xf@?\\Gf@YlBpAf@Lh@?l@UPU\\IHWJKx@SzAYTOp@Kz@?d@MpBFZHf@?ZEj@e@hAc@rBD?EPFHGDOf@WrAa@~AIJU^KTR^JrAGr@YD?NFl@a@PAZWTG`@?|@JDH@KNJ|@?FTPHNTFQFCf@FXIACHG~@BXQXDNK^?RDJKZ@LLP@?DXENDDETRLEn@BTJI@F@LAIIGDBBJEHRVEHKE?BKARL@I?FLELJJ?KBXJHM?FCAKFRC?K]BOSCBCGK?WBIPCTYB?EB@F?EDCE?@E@FEEDBSDGNQFERQIMRe@S?FEFMQKFQKm@K_@Bi@W_@Ny@Es@Po@C{@Xe@CKFAFUUw@Kq@Uq@FeA\\OOYGu@f@UDQGq@T{AE[Wm@Nc@Pi@GWHu@UWHGL@NIDMb@_@b@B@a@^c@R@Hc@HMJ_@EoBXWSQDs@YiAE_@JaC@uAh@uCRc@`Ao@H[AoBg@uBFe@La@UG@CFc@KkAZEJ@TKBSn@_@ROGSDEMw@US?AMUDKMk@?UDi@GsARc@XWM{AN{AWWJ?KCC?FIHS@sAYkBh@]A[Ps@Vw@Fe@RGNYNIJ?LJLGD[r@KXBBKDEVHl@FHRDHj@NRUVCVUh@Bt@CHBPIZi@v@IVmAdAWd@a@^o@xAs@T_@\\IVaChBI^AnA_@d@FHCFBGAFAMWDiAr@aAv@QCk@Zq@LW^o@`@Wl@AROVI`ABx@[HSVDXCPHF?LOnA~ApAbAJ|Ar@\\l@RtAFrAOxAGNkDLkC_@QLARDl@b@bBh@jFVlARpB?dAJn@Vl@^b@`At@?DZJ",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": true,
    "visibility": "only_me",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      37.018783,
      -112.025334
    ],
    "end_latlng": [
      37.018788,
      -112.025284
    ],
    "average_speed": 0.934,
    "max_speed": 2.26,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 1589.3,
    "elev_low": 1473.1,
    "upload_id": 20403435265,
    "upload_id_str": "20403435265",
    "external_id": "7665FF89-99AF-4CDA-8DD2-98FF103FF45D-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 6,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Butler Fork",
    "distance": 3299.8,
    "moving_time": 3377,
    "elapsed_time": 3463,
    "total_elevation_gain": 252.3,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 19203035026,
    "id_str": "19203035026",
    "start_date": "2026-07-06T15:32:25Z",
    "start_date_local": "2026-07-06T09:32:25Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 6,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a19203035026",
      "summary_polyline": "elbwFb_phTQPE?_@\\G@]\\WBKZEDAPGJCREHOHIZA^EBKVKJ]PUV]LKAGDB@E@ECO@KGC?ACICEAA@IAOIW?QCW?SDMESBOCM@q@RGHG@ADC@?BA@CEKNE@ELIDu@EGE?CKG]KGBMEE@CCABEA?DC@?CICCB?DAACB?EAHAA?JGEKBOHUF_@RKHKB[VG?ILE@?DGAKJCNCAGDAEOBAB]RWPGHMBi@Xg@NOJ[DYEe@AK@q@CkBHMEGIACG?CGOECKECICI?IEG@EGKCSIK?KEe@Wy@WK?KCOQ]o@EAIKMCEIEAEGO?MHAAIGWIUWIEEI]GUKc@m@I{@EOEGAKEBETC@IGAECACOIOKEEGu@KC@q@OSAOGACYOQCE@EEG@EGIA@EAFPDJ?A@B@LFBCDDLDFFbATDAFFB?DE\\JV@DHH@JR@JPRDE?QFGBJDBBJ@RA?DHDb@?APVA?TXJ?DDPFD??CJPVNHJVLDD@@NMJ?RNHBLJF@`@|@PJLAJB`@PTD\\VTDLFPDHHF?DBJADBHFBHPFBDF@@DHHPDFCPBVGJBd@Ed@@NCFBZERDJDLAt@Up@_@TCFMd@WRQRIBIB@FMLE@CXIBEJ?PQPCNMJABELABIPG@APE?ELKLEN@JFV?FDd@HHDJ?PDLCh@_@DCD?JIJCJM\\G\\BPEd@@JCDHJCXDF?AABBD?h@NRDDEF@HE?ATOFAFBXQTSZe@D]FM?GPULm@Pc@BAFDHCDMHELSH?DCFOD?l@g@",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.649224,
      -111.661885
    ],
    "end_latlng": [
      40.649371,
      -111.661545
    ],
    "average_speed": 0.977,
    "max_speed": 2.46,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 2427.9,
    "elev_low": 2166.8,
    "upload_id": 20319913979,
    "upload_id_str": "20319913979",
    "external_id": "DC3C6AFD-F150-4C1E-9C19-4B3A5D0A91C5-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 4,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Brighton Lakes",
    "distance": 8637.8,
    "moving_time": 8816,
    "elapsed_time": 13532,
    "total_elevation_gain": 419.9,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 19196115019,
    "id_str": "19196115019",
    "start_date": "2026-07-05T22:24:28Z",
    "start_date_local": "2026-07-05T16:24:28Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 6,
    "comment_count": 2,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a19196115019",
      "summary_polyline": "mgxvFtt`hTbAeBxAi@f@?`@Un@NlB?t@F~@PQqATg@fABlBX~A@hCUd@P~@GbAg@AHZ}A\\Av@c@TDb@]\\HfAbApA`@p@ALDLIKMR@b@Rj@^Z?XFNb@DCFRIv@GJO?K\\@jEJ|@e@bAb@fAHn@E?Rd@BRAv@[~@?PSVMz@Wd@BLe@`ALJOb@C`@nA\\^`@R@Lr@P@CRPFLXDPG@ALZJDJNACGPU`BSLKIIxAdAVJb@Jv@WRJD^\\XBRMz@?|@JPDr@NMKr@BPSBFRI^BLE@VREXHEAHL??FJMHRb@Jx@UPJSIe@JAo@Ri@DiATQDU\\FJb@?P\\BARVPVv@TFFR`@_ATMRXKCHBBRd@A\\L@PVESJDVD?CJNBQ\\HGNLAGEHFGEHTLKNGC@v@MDJD@^NDI@HAEJVL@MNCBXBOXDCJI?RIAkA?FHC?IAFF?c@OJKOBHFBE?NQG?HEAHGGAM?IH@OE?FQO@JIBBa@FEGFCI?CWKCLJ?_@UEFa@Km@SBAQQG_@@Wo@c@ONWFc@\\GFOJJNCh@FNJBGQOKo@MW?Sk@k@J@Q?HBGWUMGUQM[s@eBi@Ko@BQh@QpBbAv@JtA~@pB@Xb@AVP\\d@@DJ^fBDAEDTPNp@JDB^DAQvAh@PR\\LZHx@\\~@\\\\jAER`@ZBXRTDHIRDGm@EATWEC@NxB\\BL`@@FPP@TRJXF`AKzAYtA]h@}@CQFANa@NUCMLSGMe@OBFIGKIACUSVGZc@XMh@e@oDSa@Ik@QOIeAGBDUE@[}CGgBg@_Aa@CBGGKHEDUMKH]Ek@UWAW[c@Ks@BESc@e@GS[Y}@q@GaAHu@q@CFHDBMCJGEFGJAM?BJQO@F@GYKq@MYKoAq@WA]PCHHn@EJSAQWQe@ORM?W]CYE?GSc@CCKKFm@a@_@k@QGCFUGIc@SIQ_@MCAQMGRc@Y?EICOUMSCBD@GSQo@UNi@OODUGOHEMg@DUF}@Qq@]KJIKe@D@AFBQEOMEOa@_@QIBoAgBc@GQNMMLCJ]IWFAHq@Ga@@_AZa@D[CUDEKKCa@k@@GHcBo@}C_@]_@GH@Ui@_@u@[e@?YPC`@Q`@a@@Et@DCi@r@iBVgAKwARkDO]Fq@Ws@BOl@NlA]QuAK}CQYTc@Ai@Z_ATg@xA",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.598063,
      -111.584849
    ],
    "end_latlng": [
      40.59807,
      -111.584774
    ],
    "average_speed": 0.98,
    "max_speed": 7.169,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 3029,
    "elev_low": 2671,
    "upload_id": 20312887291,
    "upload_id_str": "20312887291",
    "external_id": "94F25E79-E688-416B-B511-50ECE41E70A4-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 5,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Afternoon Hike",
    "distance": 2256.9,
    "moving_time": 1949,
    "elapsed_time": 3882,
    "total_elevation_gain": 15.6,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 19117472411,
    "id_str": "19117472411",
    "start_date": "2026-06-29T23:44:28Z",
    "start_date_local": "2026-06-29T17:44:28Z",
    "timezone": "(GMT-07:00) America/Boise",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 4,
    "comment_count": 1,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a19117472411",
      "summary_polyline": "genhG`tzjT[O_ACg@OIEOQK_@?BBA[_@UEUMEIU?z@{J{@|JBFEEDBe@v@JGAEV]BSH?DA@EC@B?DD?FZDHABBDRHFJRFZFPVJD?PFz@LDARFPJZX^j@\\Rd@BFG@AEC@D?CLFb@@VJb@HHBDJAC?@FC\\DHMPDD??FD?P?RB`@GDBABIFE?B?DGA@DFXRZLd@LJJVFL@L_@ZoBBIVCJFFPPTH`@E^C??QGAUSU[MMB?GEGSMMBC?FEGGE@MAC@K@BC@@C?@DADGB?BDBNIFFKDABj@A@C??@KKIAMD@JHNBA?AA@@CB@@PDDH@DBDCFMCIB?EIBECEEB@?K`@U|AFLD\\LNTf@ZZ^Nn@H@DBAVBFOC@@DHJj@Vv@Xf@`@FBHABFJH^RF@AIEOKI?ENBLRTJ\\BPG@E@L`@Vi@YU@QG@@K?OKMSg@QG?CDGCWOMOGAKF]MKDAJJL?FB?B@BCCAD?CHBAAA?BEMCD@AIMKIQc@e@Mq@GYK",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      43.494359,
      -112.044883
    ],
    "end_latlng": [
      43.494123,
      -112.045027
    ],
    "average_speed": 1.158,
    "max_speed": 2.263,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 1436.9,
    "elev_low": 1428.8,
    "upload_id": 20233037601,
    "upload_id_str": "20233037601",
    "external_id": "AF57725A-17E0-4133-BD72-C312A54FA0EC-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 7,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Lunch Hike",
    "distance": 5751.7,
    "moving_time": 4545,
    "elapsed_time": 4870,
    "total_elevation_gain": 158.8,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 19040462762,
    "id_str": "19040462762",
    "start_date": "2026-06-23T18:39:59Z",
    "start_date_local": "2026-06-23T12:39:59Z",
    "timezone": "(GMT-07:00) America/Edmonton",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 8,
    "comment_count": 1,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a19040462762",
      "summary_polyline": "an{vH`n~wTG@CFDXA`@@RFVATOd@Gd@Qd@O^U\\Q^ED@DPPND?@O?W]CFGFK`@MNA\\GVFXFFF`@IXCd@BPE\\Ir@Od@C`@Hd@BXAJAAABBHE~@@PPp@PIPo@RW@@BATa@?KBU?YBGAM@MHE@CHAF??C@BNLJ?B@DJC@?HNP?HLJ?CBNJFFPJ@BBJZ@|@At@EP?^OhAO~BSr@GJ@HDCCEAf@FVFEEN@t@LtA?ZP~ACRCQB_@Oy@GQEe@?y@C[@QI]AWUcAGcAPgABMB?GBF]BC?@BE?IBE@QAq@BUDG?@DMBE\\I@E?GIVULEFCXBREP@DG?@LEPFs@Ai@@KFQHIJENKBWAA?@SFH@FECUS]OKIAYFCBGPE`@KHK?KGEK@OIs@GHGV[TWx@IBIFE?CCSeADSDs@Cu@EM?SHo@J_@@QFU?m@Hw@CSMYAYH_ALKJ_@V_@JSNSB?D[Zu@DUFIFYBK?QGc@@s@EY\\CHEVe@TUr@mB^w@t@k@\\c@HCBEH?BMLIFAH@NWB?BGJCFGDAAC@KKE]BEIWOCDOEGHUEKFCFa@HGDC??CC@?HMPMFCJMRMDIFELKJGNQJWFGK]K_@g@cBKMOO@]EG@WGIMi@c@We@i@o@k@qAGUGK@MAE]MAEMQOICGQOWOOCI@YGOISSOEYa@Yg@AKC?@CDA@GCw@Rk@Mu@CuGBk@Cq@DmAEyABaEI}BDcA?oCIcCQi@KeBGOMKE@KNANM\\QRC?IDGEEBK`@?TELC@KIGDIM?CBC?DAGE?ABB?CKa@]MOYKi@?MGI@GFc@HGA]UWAOEUMC@MEK?UGWMWAMCKIUGOMUCSK[[WOIOQE]A[IG@aAu@IAECI?OD_@U]MKGUE[MwBQ?@I?YEODICAIZi@Kk@AQRoBDC?AC?B[He@CAa@c@[OIIG?{@c@iEuCm@e@GSIkB@CMa@s@IYGQK",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      51.098213,
      -114.19186
    ],
    "end_latlng": [
      51.112543,
      -114.173684
    ],
    "average_speed": 1.266,
    "max_speed": 3.1,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 1152.8,
    "elev_low": 1071.3,
    "upload_id": 20154766126,
    "upload_id_str": "20154766126",
    "external_id": "ED66C509-D3E0-4A94-B378-D590BFE67909-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 3,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Lunch Hike",
    "distance": 2869.7,
    "moving_time": 2451,
    "elapsed_time": 3146,
    "total_elevation_gain": 34.8,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 19038591220,
    "id_str": "19038591220",
    "start_date": "2026-06-20T17:22:23Z",
    "start_date_local": "2026-06-20T11:22:23Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 5,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a19038591220",
      "summary_polyline": "a`bhHv_gtTEXAAEh@WXGh@INQf@KN?FMJOFCDGVAXEFARELEZ?b@EdAKd@@ZIf@AZE\\Mb@AT]vAC\\?VAF@\\G`AO`AEl@Q`B?REFE^Cz@CDIp@?PGVCX@t@R`AAdALv@@RGbBGRGx@ITARHHj@\\VXR\\BDZp@ZhAD`@?`@BHNP@JGJAHC@B@C??EAB@?EB?EFABC@KFE@KGG?BDG@GD@GTAKCBMKEs@QcAIKGYEECKEG?EC?MWg@m@QIKKOIGKNu@Jy@?u@Hc@Ae@Mm@@qAUgA?u@P{@AG@[BUBE@e@AEF]AIFK?c@NcA@[Fo@@GADHECG?YBQAQF[Bk@BIA]AC?KLm@La@BYNm@Fu@H_@@SAQBS@YJYA_@FaALYN_AFKRIXq@To@@_@PMDGHm@?UAHBE",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      48.676265,
      -113.580854
    ],
    "end_latlng": [
      48.67626,
      -113.580847
    ],
    "average_speed": 1.171,
    "max_speed": 2.38,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 1401.7,
    "elev_low": 1381.8,
    "upload_id": 20152876778,
    "upload_id_str": "20152876778",
    "external_id": "8D57206D-8F74-47D8-880A-5EE45149E9CB-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Afternoon Stand Up Paddling",
    "distance": 3062.5,
    "moving_time": 3592,
    "elapsed_time": 17065,
    "total_elevation_gain": 18.5,
    "type": "StandUpPaddling",
    "sport_type": "StandUpPaddling",
    "device_name": "Strava App",
    "id": 18924085102,
    "id_str": "18924085102",
    "start_date": "2026-06-14T20:47:44Z",
    "start_date_local": "2026-06-14T14:47:44Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 6,
    "comment_count": 1,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18924085102",
      "summary_polyline": "{dzwF`k}fT|@aDL]pAqBf@m@LGACBGABCIGCEI?QDKNQRQ@FQLMRC@CQB?CQNi@R_@FOT]`AgA\\k@POd@w@H_@JUBQAAMC?WFAEG@CYPORMLOXSXIFK@AACBGTSXKb@QVM`@MT?JETW`@OPUd@OTM^Gb@I|@GNGD?UAEDDJz@@\\Cz@P|AEDEWEC?@HTHD?C?@@?AABAECCYAg@B?C??AB@C?AE?a@@OFKBALDDDDCA?@@A@AE@BIIA@QTITBYASCEFD@LE\\ELW^Yt@Id@CXEJKLC?BUDB?LMRm@b@WHe@\\_@NAAGNMR]`@w@b@IB?CC?QXQLAEOEGGKSCQ@]CEPCDCJ?AGCEAIDAEFKh@OP@pAU~@E\\Od@IHGBGCIMIHI@KKCIKAMH?F?Ac@b@i@TE?AIABC\\ZpA?XC^ETKNULGPCCD??G@FAA@B?CCBBAAD?G?BA@?AA@@C@??EQ[BUK@e@Ek@D[Aa@Bm@@IE@@C@@@@A?DH@@CCKB@GAF@AHAMC@ABDCDFEA?GADGBB@CADCC?@FC?BEA??BFIDDACKABFC@DKDFIE@BC@?@FGBBAEG@AL?GDE@@?AE@?B@G@@@?DFIFAA?E?@BKD@AAGB?B@@A@@AC@?CB@ADF@BICE@A@BCA@BAEABAA?@@CA?CH?C?D?EAB@A@@A?@EAFAADGB@@B?C?@@AGAC@?D?EBADDCEDBC??CC?EJBBCC@??BD?IC@CA?BFHC?CCG@BE?F?AB?AEAF?ADBAEA@C?DC?@EA@AA@BBA?DBCCB@AECABE@B@?EA@@@AA@??DACBADCBBE??EBF?AAA@?A?@B?CAB@AA??AAABBAA@??@@AC??ABDC?@C?@AC@BAEBHCA@CCC@DCECJBGBBAA?AAFFAfAW`AQp@At@G",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.77193,
      -111.40496
    ],
    "end_latlng": [
      40.771795,
      -111.40651
    ],
    "average_speed": 0.853,
    "max_speed": 2.1,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 1852.3,
    "elev_low": 1841.3,
    "upload_id": 20036667873,
    "upload_id_str": "20036667873",
    "external_id": "30BE23F6-3513-4C4C-AA7C-ED6162D69998-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Afternoon Hike",
    "distance": 10267.9,
    "moving_time": 7366,
    "elapsed_time": 7677,
    "total_elevation_gain": 205.8,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18922461748,
    "id_str": "18922461748",
    "start_date": "2026-06-13T23:42:22Z",
    "start_date_local": "2026-06-13T17:42:22Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 4,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18922461748",
      "summary_polyline": "ixitFd}zfTAc@u@}B?q@[yADg@KWCkBPq@@k@NWJJb@yATi@Mc@MaCm@yAu@y@IUB}@oAg@kByBy@E{@o@Wu@g@g@[kAD[aAiDw@aA_Aw@gCqAg@Bq@e@_Ck@q@g@_AGw@g@UFQq@c@]iA_@_B]KQsAc@gAFe@We@g@Kq@Y_@u@GiAyAm@c@c@Eo@}@OB_@k@}@a@}@}@Io@w@s@gAOs@uACo@_AaAy@a@}@gAMi@c@_@?QWOYy@M?Ee@SGe@eAK_AMo@Wc@A]Wc@K@Yo@KoBcAgCH_AG_@JOm@w@Bg@PGUe@ScAIaAi@y@Uo@AU[[Cu@Yu@o@mA]]Oa@@c@c@QY{Ae@i@?Ym@mAGc@c@_@Ge@u@o@UqADy@g@cAWQ?UHIEa@Qu@c@[U_BeAcAc@LmAkBe@YOw@g@kA_@i@O?FOSSEg@m@i@We@Au@[c@A]JSe@gAa@[aASq@`@oAq@u@Kc@}@e@s@K@Q[u@KDKc@g@BY]aAYGOm@y@k@[P[OOe@eAk@Y]{@SGm@i@e@sAi@u@mAIiAa@e@WE@KDRt@^PpAn@nAhAZ\\`@Z|@lBz@v@`Ab@NTMNHj@h@\\pA^LJTA`@ZV?Ld@Ab@d@R@~@rBlCt@j@]hBbAXx@KX\\n@D~@Td@\\JO?z@xACTJCbAvBFEEPPf@h@TjA`Bd@S`AjBPfAZZ^tAEb@r@dAF|AXfAr@`@Df@VRRt@VVTrA^b@VjA`@^P`AdAbBb@fBbAxBZ|@r@~D^H@fASHF|@Gh@v@dBTlCXf@N@Rb@A`@TXp@~Cf@ZHd@b@d@?\\b@VX^Db@hAnAj@TRd@`@NRb@p@nB^Az@b@b@h@Pt@j@n@l@Lx@`Aj@PXb@f@JdBvBbAPZ`@Hp@^`@f@VxAArAx@dD~@b@\\Tn@nA^t@Dn@d@jCr@\\Vz@FlB~@hA~@jAbBv@xCE`@^jA^Nf@dAv@d@ZC`@V`ClCf@BFXGj@t@bAp@~AV|CHJ?\\_@\\Gn@URUCSbBFhDh@xDj@`BA^",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.195339,
      -111.391656
    ],
    "end_latlng": [
      40.19531,
      -111.391655
    ],
    "average_speed": 1.394,
    "max_speed": 3.54,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 2048.7,
    "elev_low": 1841.9,
    "upload_id": 20035012608,
    "upload_id_str": "20035012608",
    "external_id": "CE208B4C-B855-41DD-9EB5-2DEB90114147-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Dinosaur NP",
    "distance": 2924.6,
    "moving_time": 2600,
    "elapsed_time": 2976,
    "total_elevation_gain": 68.9,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18834845134,
    "id_str": "18834845134",
    "start_date": "2026-06-07T17:07:51Z",
    "start_date_local": "2026-06-07T11:07:51Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 5,
    "comment_count": 3,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18834845134",
      "summary_polyline": "ovyuFfpbzSa@QUCMOJLVDd@TRN\\NT?FDJ?JNCVMNGZAlBAFGJ?r@EJ?NGJBHET@JHFFAPa@p@_A^_@LELHJNNBBHC`@EPMbA?GDYAIFq@GBEDAFID@FG?IM@R?AD@CABBA@?BDDCJEE?@CI@A@@AEJMAC?BBDCFEK@GBHBAGV?MCD?A?RBLAJ@CJ?EEID@IB@AB?C?@CAA@@ACADAACBD?G@BC?ACB@AD?JACBBBACKBG@IC?D?EOCDBDIJDA@EBCEFF?IKFCCBBHICBMEE?GDEB??DC@B?GED??G?FEDEADM?J@CDAAEGE@AA@@AACBB?CHEJABEBOBDTB^ML?CBK@IASJGCEMWEKo@@O@XENMHc@`@q@~@WPIADa@AODG@QBG?QBICE@QFUD{AAMH_@LO@UDINELBNL@FAJB@TL`@@NNF?PM@CEG@[d@y@NOPEPJL?TDZEH@FFFGHCf@aBb@g@TKNCLDFA^U`@_@NE\\Ad@DJHHR@X@RDH@XE`@@XAx@IXBh@EH@^Kp@@JCLBf@EF?TE\\CpAIXDZA\\EZBd@CP@r@ARKVEX?LIpABf@K|@?l@Gb@Sn@G\\?z@Ez@Fh@Kb@MxA",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.439856,
      -109.299314
    ],
    "end_latlng": [
      40.438265,
      -109.307198
    ],
    "average_speed": 1.125,
    "max_speed": 3.04,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 1530.2,
    "elev_low": 1461.1,
    "upload_id": 19945975523,
    "upload_id_str": "19945975523",
    "external_id": "EB533817-876F-40AA-BB0E-AA2079EF7F77-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 7,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Morning Hike",
    "distance": 4889.6,
    "moving_time": 3397,
    "elapsed_time": 3696,
    "total_elevation_gain": 32.9,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18782220444,
    "id_str": "18782220444",
    "start_date": "2026-06-04T08:26:59Z",
    "start_date_local": "2026-06-04T10:26:59Z",
    "timezone": "(GMT+01:00) Europe/Paris",
    "utc_offset": 7200,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 4,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a18782220444",
      "summary_polyline": "qdmfHupnOJKH[?IGI?C?A@DBALWH]Tc@Pk@LQTy@NQDYJM?GN[Zg@LKFKFQNSJQ@MZ]NUVU`@g@FM@ESk@Ig@?@CA?YF_@Lg@Hi@SqAm@wBEEASQu@AMG[I_@KGOcAEEAOIUEGCUOa@Ce@K[IKAOCACQEIKm@DWCE?g@C[WmAK[{DuPg@gBE]o@sCA@AECBB?GE@ABBQBDCFBC?DCAE@@@AQaA{@eD}@_ESq@C?E[{AwGQq@a@mB[_@MG?UBCTOFAj@c@PILKr@i@B?HRAEDRDF@LHPRdAX~@BTHT@PPh@Jn@FLNh@f@`CL^|AzGFLpC|LPd@TlADD?LDF?HHLj@jCPf@f@`CPh@Px@J\\TlAPh@@RXbA@HFVHd@Rr@HR?FDRL\\@PTp@Nr@Db@L^Rz@FLLn@Pd@F`@Pb@HJB?fAu@d@m@HQPKXYt@i@JMb@YFIjAaAHCH?BFFALHNDL?FBL|@b@zARfAVv@HHLBb@Df@Ah@JNTVt@VnA?A[wAY{@C@?@SQeBK[O[qAIc@]iAO_A@IKQSBQLGb@WVcAp@QPcAp@k@b@k@Xc@Xc@`@s@x@WNeB`Be@ZITQPO\\?NBLC\\[r@GJI?W^IDQh@C?CDKBOd@IHANWVE?EFSh@GD?BGN?JGFEVE@EHALIPQj@A@OXIHYr@G?@LMVIb@EJCL@HCB",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      48.40655,
      2.699484
    ],
    "end_latlng": [
      48.406607,
      2.69949
    ],
    "average_speed": 1.439,
    "max_speed": 2.773,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 85.2,
    "elev_low": 61.2,
    "upload_id": 19892355003,
    "upload_id_str": "19892355003",
    "external_id": "D81CA5A0-99B7-415E-8568-0BE21E88D115-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Morning Hike",
    "distance": 9125.6,
    "moving_time": 6187,
    "elapsed_time": 6972,
    "total_elevation_gain": 57.3,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18767764940,
    "id_str": "18767764940",
    "start_date": "2026-06-03T08:38:29Z",
    "start_date_local": "2026-06-03T10:38:29Z",
    "timezone": "(GMT+01:00) Europe/Paris",
    "utc_offset": 7200,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 5,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a18767764940",
      "summary_polyline": "edmfHspnOFIEEHODg@Rc@BQ`@eAJOHYDCH[LWH]n@uAPONa@RWGUJBROJAJa@x@s@FQ?MGMW_BNaAAIBs@A[OgAu@kCOkAQ_@_@aB[aAIk@[cAMq@CeBGc@aA{DgAeFa@yA_CgKqFaUgA{EQcA[]SAIGUKK@iAn@ONSHMLQBi@d@WLYZg@VgBpA_A`@BIUVcAp@k@l@QHiAQcA_@KBIJg@Iu@[KOQ@i@QKIu@IcAa@g@Oc@Ig@QCIe@G[IQKQ^Dx@CNRLJ~@Pd@Jj@HFN^E@?B?G?JAE@BJMKNAEADFPF@HvAPr@BVV~@Jx@RlAPj@t@hELZDZNEPa@\\sBHUDERNVd@LJRd@RLNXRNRb@LLj@|@LLJ?d@u@JIJM^gAt@{AHG@KPK`AyAZSH@HXRV\\p@FFb@z@Z\\Zj@b@|@D@?HD@AJDF@UFKVcAZs@@]N_@DQRe@x@aDXm@DYZuATi@BW\\{@BWR_@FUPQA@?K@DBEEM?SKOIs@ISA]Ig@CAI]Ec@GEK]Eq@SmAMa@CUQYKi@CU`@UNQhAy@fBiAp@i@ZSJBZtAj@rBHf@L\\Fb@DJNhARj@Jv@Xx@?FRn@XtAJb@HLFd@Tt@Jn@Vv@@NGJIX@BIGJRLp@l@xBr@dDh@hBjAdFHV~@tDhBdILd@DHt@hDrCfLTpAADWPAGGRONYDKHOWIUAY@@CBCKE[Qg@Ko@u@cDIQGa@Uo@UqAKUIg@K]GYECKs@Sm@kA{ESmAg@}ACW]qA_CEqAPKCO]c@eB_@DEDO\\SN]x@AFOXOJAMGP@FIJA\\CJSV@BCDKPERU\\i@dAG^Wf@AFKJO\\i@v@GX]p@GZa@\\Ip@k@hAG|@SvB^~AXV|@ZrD|@dARzAf@`@Jh@DdDbAn@J`B`@dBh@NNN^LHJXFd@E^@b@ThACb@IZOLO@GFk@|@CTVv@XTJd@\\l@Hb@In@Kf@BNA\\L~ASx@@^Ej@WRMVEXBRLLADJGCJE?HHSJD?DGC@@BAIDG@BKLDEADE@NG@PFJCHKD]IQy@M[OSIUSQMAk@e@MCM^APKX?LC@Wf@?ZETMR[SWi@KMONYl@KBMM@IEMMOCMCAQRSb@C?c@`@MRSFGLC?BDEE@BGBI}EFg@HhDF_@DaDB?BWIe@SWUy@",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      48.406497,
      2.699529
    ],
    "end_latlng": [
      48.408378,
      2.702563
    ],
    "average_speed": 1.475,
    "max_speed": 20.54,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 85.9,
    "elev_low": 59.9,
    "upload_id": 19877643465,
    "upload_id_str": "19877643465",
    "external_id": "B448E17B-82CC-41F3-917E-96380E140F53-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Afternoon Hike",
    "distance": 3058.8,
    "moving_time": 2145,
    "elapsed_time": 2558,
    "total_elevation_gain": 12.7,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18766741279,
    "id_str": "18766741279",
    "start_date": "2026-06-02T13:14:22Z",
    "start_date_local": "2026-06-02T15:14:22Z",
    "timezone": "(GMT+01:00) Europe/Paris",
    "utc_offset": 7200,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 0,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18766741279",
      "summary_polyline": "}smfHkxmOCLEBGVEFD@AC?BECITc@RMTKJMDGHM@INE@AHKNSDKTKNGBORKDEHE?EGOWMMUs@GIEF[XCFC?OLIPGFI@WVQJS\\YHGJKAOLk@h@QXKH?FCJE@ILAFSVGPI\\@\\@CE?QJCCHLJXACB@@G?BGMAKMQO]C?@KEUWgA?@EGS_AUs@Mm@IM[oAEIQm@Gc@Yu@Kg@a@wAFH?AFICA?DCAABAABAAEHSJG@@ACC??KBG^IPSPMNEVQr@o@RGr@q@BIHAH@BAACDPHBTQTGDGH?LGLYHGFKRMFON?HMVEVc@LKB?R]C@BOBAFDAGF[DELc@Dk@Rm@f@kAHYBYP[@QJMHQBAHWDYFCDIBWCCCB?K@GD?N_@?]DMB[JYFAAKN]Ae@Fe@?IHSLG\\Jp@^@ACD@F?k@UxCLgCE@JQDAO@DABB?HBEABLkAE\\Ah@C_@BEAD@rACyA?JDFEDAADFCESVDOLGBIAHACC@FIGT@QELH?@GGHGd@Fs@FA@BCA?FCA?FCHBK@HC@@IAHAG?JERN_@EBDg@Cf@@EELACQ?KGG@WOKd@C?ADONCJIJI`@BNED?JUf@?LEF@DENELONE\\EJE?AFPNBJDD@FJXJFJRFV",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": true,
    "visibility": "only_me",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      48.406841,
      2.699123
    ],
    "end_latlng": [
      48.406497,
      2.699556
    ],
    "average_speed": 1.426,
    "max_speed": 7.975,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 94.3,
    "elev_low": 81.3,
    "upload_id": 19876601420,
    "upload_id_str": "19876601420",
    "external_id": "943A878C-4652-40C8-B931-7CF372AE0C91-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Evening Hike",
    "distance": 6126.8,
    "moving_time": 4500,
    "elapsed_time": 4832,
    "total_elevation_gain": 63.4,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18746583562,
    "id_str": "18746583562",
    "start_date": "2026-06-01T18:20:34Z",
    "start_date_local": "2026-06-01T20:20:34Z",
    "timezone": "(GMT+01:00) Europe/Paris",
    "utc_offset": 7200,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 6,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18746583562",
      "summary_polyline": "sumfHg|mOIHCAMTWREHGTGFOHKL[TG@WXKFSVKX[b@CAe@f@QZQRWRU^EAIJC@QNGNGDAF]@MFKH@BSPEHIDABMJINIB[f@KFIRMt@@ZACCBAC[JACEBCI?BE@CC?@EHBBEALOJA@AA?NENKR]LODSZg@DSZ]?ANMNk@HSNSb@OFBFC^[h@m@TGJINWG@Wr@GFE?EHEBQTWTg@n@IBKASHIDCFMDOZ@BOPMH?BIJO@GDi@|@G?GIAFK?QFSi@Ky@B@N^Fp@?FCHDh@E@O^St@Yd@Yt@IHCP?DK\\_@r@K\\W`@M^MTKHQl@MXAVGTWtAc@xDRx@C|@Ux@E?[d@]ZKVAJEDCPK\\Ih@QlAWlCILGBCH]\\ILc@XKLU`@k@l@CHQX_@^?TEBCHGf@@HCHEl@EHAXEXGH?PCRQb@C^EJI`AKl@K~@C@Ov@O`@CXGH@JE^If@EHGRAj@Mh@C@@DEP?VIV@BI`@Ir@EPATIPCVEDGTE\\?R]dBCBAA?DIAGFCAi@BMA]LECi@HMAABEA[JKCQFUA?CDEFE@OAIM[CDG]EOCCEDCCAMEBIECIFIDSPA?IGGGSUSIWGw@CECKECISGo@UGGIAIFM?CGIAGUEFG@@AATMCAEMYGGUBQEWIMBMEa@QYFGB?@EAIK@EACBEG?SCA@OCAAKGIEM@YIi@KSAMGMG?EGIYKq@MWCYIMEaAQUCQ?KCKKQ?GI[CWEIGk@GSGCO_AGMGa@O]Ik@Wo@CWYmASm@ECEUKWIIIY[u@Oi@AIKIA@CMKSGO?GHE?N@?BYZWf@oAV_@Pi@d@y@@J@CBQFWn@mAVq@B`@@YHKD?BYNWDQDAHQHSJG@GFG@QLWHKBMLQ?EVc@?GJ[RQDOB?@IPQFOBODEDMJO?BNQ@GLQPi@Za@FQDGD??MVg@NOd@}@`@[V]PKBE`@[PWHEFIJIXi@HAFKXMP]FCRSDCNUTMz@o@JOFOTSD@DGTMVUN_@HE^]FCXYVMJLHDP@b@Eb@@h@GXBfAAPA@CV@NGJ@PG^Jl@QDDF?BDB?ABD?XI@BDAHIDONKJYNIHKFOB?@ELGDQJCVSHADIJM`@MLKP?PGBGPED@@LB?b@Y\\If@m@TOBGJ?JQJMDADGD@LILUVUDITFBFRPDFBXB?BCFB^d@J@FDPXB@JT@CNTJJB?HNXDFJPF",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      48.406546,
      2.699358
    ],
    "end_latlng": [
      48.406533,
      2.699542
    ],
    "average_speed": 1.362,
    "max_speed": 3.3,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 138.1,
    "elev_low": 84.8,
    "upload_id": 19856095552,
    "upload_id_str": "19856095552",
    "external_id": "25DFC5DD-C34C-41A2-ADB4-CC9F2827125A-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Tour de Odeceixe",
    "distance": 13738.1,
    "moving_time": 10690,
    "elapsed_time": 12282,
    "total_elevation_gain": 153.3,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18690566960,
    "id_str": "18690566960",
    "start_date": "2026-05-28T10:14:19Z",
    "start_date_local": "2026-05-28T11:14:19Z",
    "timezone": "(GMT+00:00) Europe/Lisbon",
    "utc_offset": 3600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 6,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a18690566960",
      "summary_polyline": "kdncFnopt@FPHFLf@@RIT}D`AKJA\\nG|f@@b@M`CBPb@VOz@CZRzBCXUv@SxAMf@gAdCe@r@c@VsAd@}@T}@DURITA\\Pb@tE|CN^Fl@MrA}@pGOp@_@b@eB~@mAnBKZ?zBJj@JnCGh@Uh@E\\ZdB@d@Yb@uAj@k@d@uA`Co@t@_DhAmDnDqAfB_@\\oCbA[PALs@dAm@h@q@Ho@XILOp@Ed@Cn@\\x@^j@t@p@nABzAa@^SR@HRAvAFPTPd@Gp@]vAwBb@?z@`@^`@Jr@BhAEXKFJAFN`@tCDv@GbA@vAJd@\\f@d@pAZzAV`@nAZjABJ\\R?`@^N~@x@l@b@?`@WRDVKf@?j@j@p@lAb@\\x@FZRXEFDF\\b@EXDNFn@Sf@Dv@Q|@LZV^D\\d@l@ZV`@d@H~AjA?LTVvAx@Nb@l@r@x@Hb@^XCh@o@XKPOPGRCFKX?HFn@AjAOXP`@BXMT?AFJK`@TP@p@RDFfAJp@OVF^Ax@Yx@e@p@AHKz@Av@Sn@FRGr@@RGx@L\\@TRNBLHJPR?HHp@RNRBR^GPk@FCLRZC`@\\h@VZQp@A^UFBb@EnA]f@oAG]H_@LSFu@HWPQFs@]{AEo@~@kCJg@@OC]q@kCa@g@UMQ]Mk@Co@d@s@dAy@vDoDxBmEp@u@r@YlCk@dBCl@c@vDsDNAL\\Cc@DSxCkC`AeAdCkEn@yA^oApFoUlBuFXuANoACiAYkC?}@NcBXeAHICQj@cAG?\\[`@u@Pe@LgA`Ai@HQTOGqBE]a@aAQ{Ao@aCXjAHn@sAfBWNU?o@WuKaEY@wDz@LAGBaCd@YKcBuAkBmAg@IeCNoKoEk@IqCC{BlA]DKJ{BEu@FELMCIQC?SXFFCPUXOZGf@Wx@e@b@[t@QPkJtDWEcBq@IBIM{@]oG{Bm@c@qBiDGa@d@yDNGDI`@sCUCH?GAFa@CEBDG`@LBXy@EWLu@@a@COWWQKGF}@cAiA_AKWB}@b@uGS_AMEs@BUQ[aDDa@h@aA~A_CAJ@I^s@AqCAD?E_@OUPYFqB[s@AJDCGiB]D@w@WP@mASiA_@q@]P@iBs@u@o@BBB@iAeABCKABQ[q@AK",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      37.432541,
      -8.770089
    ],
    "end_latlng": [
      37.432526,
      -8.769376
    ],
    "average_speed": 1.285,
    "max_speed": 2.588,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 90.5,
    "elev_low": 4,
    "upload_id": 19799014715,
    "upload_id_str": "19799014715",
    "external_id": "7A368F50-08AE-4B88-A4CE-65E12EF03029-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 3,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Fisherman's Way Day 4",
    "distance": 20437.8,
    "moving_time": 17556,
    "elapsed_time": 31603,
    "total_elevation_gain": 373.7,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18690567360,
    "id_str": "18690567360",
    "start_date": "2026-05-27T09:34:15Z",
    "start_date_local": "2026-05-27T10:34:15Z",
    "timezone": "(GMT+00:00) Europe/Lisbon",
    "utc_offset": 3600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 6,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a18690567360",
      "summary_polyline": "gi`dFxfst@fD_BbAjAx@DTOVaAfAiA~CXTPDl@\\CXi@d@uDdBhB`ATn@WWlBHRlC`A~AbCv@d@vBg@bCsAbAAbAf@]fARNAb@f@Cz@Tl@RbB`Cd@Rh@K`A~@r@QlAoBpAZnApAhA\\fFqBdE[zH_Cd@\\p@zAGrALhBhD}@Vt@tA~@t@_AdAU`BtAb@x@nBb@h@k@xBg@rHi@fBZp@Q^hBhClELf@Qp@fCzAlDi@`A_Az@En@aAp@U^aAU}ApBaCZXv@xCf@j@fA^pAxBlAv@KdFvDv@`CtBxA`@vBB`AGtDoExB_@nFIfBk@~@D~@zACv@\\Dl@`BTD\\|BlApARn@Kb@TNnCw@Pk@~BuA|@b@x@|AB\\t@PfAwAKQb@w@lAgAfBCdAa@|@NhChC|AHB{@l@w@nEoQ~D}KvGlFfBbBl@vBBMCP\\SfATT[TNn@zAXlBfB~AH\\Un@{@XwAlBsDxBcA|B^VjBbEfA`@h@dA|AbATv@^\\~@GrAuAbBo@jBQvAtAh@hB~Am@f@RvBUd@\\zA}B`@uBpFa@XX\\dCf@h@ZrAm@jGv@x@|BmAf@iAzBe@vBBzBcABSr@SbA_AxADbBs@b@B`AmA^CXo@p@_@z@aCfCm@^rA^LfCqATx@Ch@JKCu@Ah@MCBe@`Ai@z@`@h@Gh@yATRER`@dABbCz@JpA_A?h@~A~@LzAP`Al@~ATJfCGnA}Br@[tB@`EpAfE{BdFm@rDp@rC~GbCDxAs@vCjAxAs@`CCj@e@pErDl@NpBWhBsBh@A|@w@v@SNkBzB@lAh@Wj@I~BhEVlAf@p@~CtCiA|ARj@}@UoFD{E`@aBFaCq@cBD}@Z]fA}DfBkCpBqAfCmCTHLzAj@JvDmEdBtBxBzG]fBkApBR|AQTAh@k@AuGh@gAl@kDT?nCTn@c@rA`@hAxCL|@j@fAFl@EpA_BTSj@Hx@rAAb@Pb@A[EPMOu@mPZy@`@NRg@hDUxCqCnC{F~DeHVuAGu@}AaBaB[qA{@Is@r@cErBgFtIaD@g@o@mAy@uDEeA`@qBD}A`AyBhCoCZiAaBmILcHUwBiF}PsAcBAeCmBuAMk@|@cFlBgBCsDbAcD\\kDMaHjAkDPmF\\sBx@oBbAi@p@DvH|HBt@iBfFIlHDb@lAHb@f@",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      37.527568,
      -8.784491
    ],
    "end_latlng": [
      37.432465,
      -8.770538
    ],
    "average_speed": 1.164,
    "max_speed": 12.764,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 62.1,
    "elev_low": 0,
    "upload_id": 19799014987,
    "upload_id_str": "19799014987",
    "external_id": "0D602D21-5325-48A1-9135-5140050EE9CD-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 3,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Fisherman's Way Day 3",
    "distance": 22142,
    "moving_time": 17401,
    "elapsed_time": 24841,
    "total_elevation_gain": 212.3,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18662946782,
    "id_str": "18662946782",
    "start_date": "2026-05-26T08:33:27Z",
    "start_date_local": "2026-05-26T09:33:27Z",
    "timezone": "(GMT+00:00) Europe/Lisbon",
    "utc_offset": 3600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 7,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a18662946782",
      "summary_polyline": "eaydFrout@MzDj@nBEd@xStNfBjBdBdDl@r@bSvF~ItAbJd@dNbCnERfCrCtAg@|A_@~@DjAt@Bd@r@rBz@R\\h@lCCtBb@@c@^q@v@Q~CzAf@F`AQ|@d@Pd@hBy@t@DpBjBvArB\\H|Di@bDcBvAFfChAx@Lx@_@`@q@RIVgAz@{Aj@QVJlCw@bG^f@n@~@pCbAIdBgApBk@hEyDhAyAz@wA\\Or@mA\\mAx@uANCLj@f@@j@t@b@MbAeBS}Al@a@jB@rAc@VFCLlApArBc@TeATOf@n@^AbAq@tB_@jETt@~AE~@t@dAIjA^BNTZ|ABz@l@j@JhAv@h@x@bCPzDMfBLp@dAn@Pt@bAR|Aj@bBnA|@B`AKxBvB`@JbBBt@pEr@Xz@tA?d@k@hAvAjAG@FGn@SfA|@v@jB[Al@t@Ef@bAoAbBeAZi@pDcQzBkIfBmChCy@jAf@xBcB|@kBrBiBrAmEpBuDTMZFVBMLv@Tj@mBa@GL_@_@mAOQSd@nAk@FfCM?CJj@]i@TLE?SJJK~@Bu@ICJGKRNJg@`ALRi@HhAhARb@WhAaAp@x@bE?j@GpAm@lC{@xGuD_@{CnC_EdGc@xAqAfBWHYvAm@r@SlA@x@Zh@@ZTKbCbCbB@`B`DjBu@JZVYl@CZV?TZDJb@`@VRx@dAjAlB}@z@qBDo@rBm@XY^cAv@u@jBIxAz@fCk@dDgAvGk@jFwCdCgDhAsBtAcB~CqA`BHpAUhAwAxBaBz@_BvDa@xAk@dCoAhABtAx@x@lAX~@ClCxBnAEXHWKGZVlAuBF]EmAN]|A]`Al@`AA`@U_@kBPcBdCmCXeA@e@p@qBJkCQ_Fa@aDDg@bQsHRnAH@M{A`IyFrFoDfDu@jDE~BeAbAy@|A@zCkEfHeC`CuBnAsBJTNCLo@j@q@NqBTKLcAjAgA`F{@nFmCjLoJb@o@rKgIlFiDVa@~@ER@JHJl@fCtBHZMLv@j@vClEzDh@PhCRf@~@^zC\\dBiAxBmDlB?QWAY|@c@@Q`@ODe@NEo@QHUEUd@g@pDe@vAi@|AhAjAtA~@IlHgJlD{Aph@cQzUkHhFqBpRkAxHALVSt@BvBXdBPHGb@hA[PLJO@NrBEbC\\x@l@~@`BPdAArCNf@n@ARZQd@F^dAf@R`@x@gB",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      37.652526,
      -8.795437
    ],
    "end_latlng": [
      37.526932,
      -8.785098
    ],
    "average_speed": 1.272,
    "max_speed": 12.127,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 76.6,
    "elev_low": 4.2,
    "upload_id": 19770880762,
    "upload_id_str": "19770880762",
    "external_id": "1340020D-F43D-401A-A90F-628082ECD390-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 4,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Fisherman's Way Day 2",
    "distance": 17765.5,
    "moving_time": 14748,
    "elapsed_time": 17372,
    "total_elevation_gain": 194.7,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18648376730,
    "id_str": "18648376730",
    "start_date": "2026-05-25T09:15:13Z",
    "start_date_local": "2026-05-25T10:15:13Z",
    "timezone": "(GMT+00:00) Europe/Lisbon",
    "utc_offset": 3600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 8,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a18648376730",
      "summary_polyline": "sbheFljrt@~@[E_@lDsAx@iAnG\\x@Sh@J_@{@U@Kc@`AXSBDf@Q@CUD^LKU]_@BFhAAOp@GOa@XHq@Rp@m@@p@EIVKbCWbCNxAQlFxBBx@JGUMBWv@u@M}@FyA}@t@@h@y@b@mBWyDgCUm@uEuFj@_Ae@k@Vc@qFuIi@[qBcD?PCUx@aAA_A_BaDmD`CaCwBc@iDDc@Hg@n@u@r@k@To@uA}C@YjCw@nL_GlXiLnLcDPbAI|AUdA?jAXfDV`@bA@ZpBf@f@^DD\\_@nAu@p@q@|D?zB\\x@DpAdAfEKj@o@Zo@dAIhA~@f@nArAf@~AMr@}@z@XrBh@v@w@^dA`GUvAp@|BP`DQbAw@VB|BU`@Az@PdB~@jB~@bAd@dFQbBXvAhAj@xJoAtEFSWyAIWYFkHnBuBh@Vt@bA~C~@`@iGCqHhC{DfAc@t@n@TlBbAtCp@n@b@dBjBhBEd@u@vAsAhAWh@E~B|@xCvA`BjAQ\\|AvBrAvANbGjCt@`ATbAHt@[l@Fr@hBQ~@f@`C^|@vAdChBnB|BCt@Mf@h@Xx@xBfBa@t@g@bL|Ad@r@x@^tAEv@zA`@tAn@^bA?t@c@|AwBK@dAc@Jc@tDyE^cAv@k@~CUlA|@jMuAnEIj@XnG?vCbCCb@jAC|Dn@|@_@fAmAdAo@^\\d@zB~@jBpBPdB{@lEfAd@r@Z?Pn@z@^?t@LNpAv@d@Cr@\\n@~@XFz@k@h@Rh@y@|Bb@vDm@bBiAAiAh@_A`Fp@Vc@x@hBHjACl@f@j@|Aj@`@h@h@?bAk@j@DAPdAUhAe@f@w@`@`@nBh@lDh@fBEPLAV|@@rCr@hA_@rBCv@j@Jv@z@nAdABbAfAtCdAdAx@RBf@a@n@n@t@EhDT~@dDj@Hx@n@r@HtAvAnAChC|@lAx@`ATXr@h@\\VxBj@n@j@\\|@KpAaAd@Er@aA~@p@hAGX^~@P~B~Dz@BrA}@`@VtAELj@n@Zx@YdAcA@eBZuA`BmBVqGPoB^gAnAgAP{@IsAgAgCcFeGc@}@Ak@fL{JnF}DDs@}@gARcCdE_@jAeAl@Or@rA~FtOdApD\\nC",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      37.730807,
      -8.784373
    ],
    "end_latlng": [
      37.652532,
      -8.795217
    ],
    "average_speed": 1.205,
    "max_speed": 8.32,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 43.4,
    "elev_low": -1,
    "upload_id": 19756023797,
    "upload_id_str": "19756023797",
    "external_id": "C6631133-7DB7-400E-BD5F-379B8BCA1D70-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 4,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Evening Hike",
    "distance": 903,
    "moving_time": 665,
    "elapsed_time": 816,
    "total_elevation_gain": 0,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18648373805,
    "id_str": "18648373805",
    "start_date": "2026-05-24T18:39:44Z",
    "start_date_local": "2026-05-24T19:39:44Z",
    "timezone": "(GMT+00:00) Europe/Lisbon",
    "utc_offset": 3600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 0,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18648373805",
      "summary_polyline": "uaheFzirt@NABELGACJEJ?HGXKPS?EFCD@D?LERWb@MHA\\UPIJMRKH?ABBBXFRABBl@@BIBANFDB",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": true,
    "visibility": "only_me",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      37.730739,
      -8.783645
    ],
    "end_latlng": [
      37.725035,
      -8.782922
    ],
    "average_speed": 1.358,
    "max_speed": 2.38,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 37.6,
    "elev_low": 23.4,
    "upload_id": 19756021709,
    "upload_id_str": "19756021709",
    "external_id": "666606BF-B666-4DD1-A5A3-B128D2ADDD86-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Fisherman's Way Day 1",
    "distance": 20478.6,
    "moving_time": 17611,
    "elapsed_time": 21780,
    "total_elevation_gain": 238.8,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18648374552,
    "id_str": "18648374552",
    "start_date": "2026-05-24T10:50:36Z",
    "start_date_local": "2026-05-24T11:50:36Z",
    "timezone": "(GMT+00:00) Europe/Lisbon",
    "utc_offset": 3600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 5,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a18648374552",
      "summary_polyline": "_{_fFryst@Il@Nd@bEzECf@^X\\lBj@UMqAHY^QQqA\\g@|AdA~@bBvDxApBnDp@wAlAEp@aAlAc@rBfBfBQx@s@t@\\z@[tALt@a@tC|@jDq@dBoCd@f@n@CdAsCZ?d@k@j@G~BaBhAWjAaDj@[`@^Mn@Hd@^a@rBTdAa@pBx@dA~@^?dBsAp@ADpAtBv@R~ApAnBNfAx@rAfAx@bB\\`A??g@Zm@lDcA^s@bCA|DwBr@Hn@{@vAKzA~@|B@v@x@Hq@Ws@Aq@v@Kx@LbBjAlCHh@h@t@D`Bk@f@~@`@\\tC?l@p@x@XV|@nBnAxC[rAm@`@VhAc@~@h@^Up@PpAk@hDbAtBGjBd@hHh@hCbAvDL`Aj@rEJvAvBf@zAGL@g@xJrBZZfCh@nFlCbGxBhAIJ[\\A~B?r@b@NWpAYv@d@tB^jBS`BZP^d@NjCXnFrAzDxA@sCp@y@hA_@pAoAhBu@rFoEfGcCbAIfEh@jF?zA[vEPdCf@xAt@x@tAZtAd@VV|@^Jd@pAv@l@^zA`@\\lAPjAYj@e@RHdH}BfELnDdB|AbAnG`GpAf@OjBPhBp@~@^zApANJ|@IaArAoA|@pA~AsBzHJnDhAzAEd@jAHpAl@lBb@hDZ`BjA|AxAjA\\dAGn@hGhCpEgAjB@l@`@b@Cr@cAjAmDx@a@~BRlA_@h@o@pAMdENbC_@`@FvAvAv@X`BnBxEtBvBf@bAQfEn@fB[pDRp@Sz@RlEq@vB@jBe@rBTlBzBl@TVhAh@~@fAh@`EPzAbANIlAl@pAO`D?dARdAaAtAMn@g@NuADoBvB{@lAV~@n@x@~AVjClFrF|Bx@GPfBh@ZhA[p@PbBRNpDKfA}@fHp@~GaAnDdBpEXzCqCp@Wx@qAn@uB\\UBmEPqAXk@Ag@n@_AdA{DCiFVa@x@_Cb@}AtA]G{AReAjA]XiBh@g@nDmAx@_@Kg@]q@i@sIj@oEpAgCpFwEhCm@tFaCjB]hAm@b@u@|EoCdAa@r@uAx@I~DcDh@u@rHoGHJGKnCaEf@c@Ba@xC|C`@K`L}JhCwDt@}Br@}@[uAB_A_@cB?}AZyDhAwBScCKDSgAH`@PDUOEc@cAOyD_C_APkABuBSiGbAqEBaDdAsDpB",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "everyone",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      37.85058,
      -8.787574
    ],
    "end_latlng": [
      37.730851,
      -8.784491
    ],
    "average_speed": 1.163,
    "max_speed": 2.7,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 45.6,
    "elev_low": -0.4,
    "upload_id": 19756021936,
    "upload_id_str": "19756021936",
    "external_id": "B1011C6C-F83D-498E-9E27-5303B5FFEC5B-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 11,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Lunch Hike",
    "distance": 8142.6,
    "moving_time": 7793,
    "elapsed_time": 20436,
    "total_elevation_gain": 109.4,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18648374731,
    "id_str": "18648374731",
    "start_date": "2026-05-23T10:18:47Z",
    "start_date_local": "2026-05-23T11:18:47Z",
    "timezone": "(GMT+00:00) Europe/Lisbon",
    "utc_offset": 3600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 0,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a18648374731",
      "summary_polyline": "iahkFpeyv@jA?FKGAH@CGBECRLaAEr@JJzBPO?BJ?[ETHKICJNKQJNj@@Lp@O]Zh@_@s@D@HEL?~@JPX@MDLHSDmAV}AIYFqAUq@YeCNc@JBII^u@Eo@Fg@SsBDQUk@Ae@EJV?CMEBDPIBTHKa@F^CSJKM??JAMVNOCU\\CKDHEI[Th@c@JBGIJKFB@F[CI]HSQaBHOMI?gAz@I_@JLKEEu@d@PEOO?HBFJOAQOBBm@[KYFOMa@?FFMDg@ILs@DP?KGZF?ESAJBY@PCA@e@Bd@?QSr@PSORFa@D@BiAGJDI?^Ea@?V?Iw@JlAk@WPFEAUEZFLC_@BNKIJL@MIHFVIe@LRKOFJGN?OFNEK?vAGCEPCW@JUVO?CD@[]AKKHE@Bu@m@n@EEf@FLk@[XCCMHSGGDKCFSs@ZIIQAVOKA[UZ_ATS\\c@IUg@Ac@NOa@mA[Dk@U_@HMi@NEMCFIMk@GFFp@GZBNHWCFFFEAIB?AF@GLCOAHYKWg@]}@Hk@iBb@QG@ON@GUEDJIKBw@s@eA_@SPkASD_@ZPFIX{ATu@`Av@Nf@Fl@MBIXHh@h@p@`@P~AMFvANLFbBX`BsBz@}@Hq@z@G\\c@NDKFDGDHIECAHCAHHKI@@HDk@JGPFA]J_BrAQd@m@l@MA@H[ZOCW\\YBUb@MGUJALBOc@ZFDQVy@n@Y@FH_@RMXk@L]p@o@\\S^M@CR]ENGm@DH^iAr@MPH@O@GNBNzAmBZ^bA~AMTP`@C`@Ph@Yf@?`@FBEIIJ?Hg@?AT?KJLc@?IXOKTZ^OIM[VHAG@LYU`@U?DBEJSHPKK?IRSGTAAG?LMALAARc@ZMGMRGVg@R_@f@OAUf@GIIRSDCPSEENESF?CPRLWg@KCEFJCB^a@`@u@\\FFOZKIDMQFJCOZb@YMEFHJKMLHLEHJ?GE?R_@Ke@T?JFIKK@NMD@UHPIDFVm@`@U[@HNAEDTNt@c@~BkCjBgA|@iA|AiATCnBwBj@UxEoEn@Sp@{@`@UNc@dB}@\\v@h@j@tBj@dFvBd@xAVlACPX~BfCKZITlDHDTbABjAFALZm@@d@bC?\\I}BDeAILDXLMM@e@kC@_@Me@Iy@Fg@GUHOxAUKyEDy@Ga@MEJu@G{@`Am@h@GPJr@]bCLZVZS@[",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": true,
    "visibility": "only_me",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      38.712882,
      -9.146247
    ],
    "end_latlng": [
      38.710679,
      -9.139103
    ],
    "average_speed": 1.045,
    "max_speed": 18.48,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 80.4,
    "elev_low": 18.9,
    "upload_id": 19756021834,
    "upload_id_str": "19756021834",
    "external_id": "9888BB98-D198-4EB3-9A30-B872D337005B-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "lisbon",
    "distance": 4799.6,
    "moving_time": 4511,
    "elapsed_time": 9715,
    "total_elevation_gain": 81.3,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18648373880,
    "id_str": "18648373880",
    "start_date": "2026-05-22T21:21:01Z",
    "start_date_local": "2026-05-22T22:21:01Z",
    "timezone": "(GMT+00:00) Europe/Lisbon",
    "utc_offset": 3600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 0,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a18648373880",
      "summary_polyline": "umgkFpkyv@F@HHA@T@CBAEE@CDF?CBDIC?AD@I?BECADBCBFAGKB?@B@CCA@CBBCA@JBAD?CECB??DGJLB?MFd@PDAKDK@H@CAEADAIBDC@?GAF@UCH@BCBBAALBE@B@ODL\\HB?CA@AF?@GAB?CFB?FFDBE@@A@FA@GFDEXPRFVNHBE@HNg@@@AADAAKDEEEB?@IJBBC?C\\Zd@NRC^DNHFPPFDEBIZIP]PK`AFNFNNJBFIBMGs@@UE]B_@CQA?B@AC@?HPANa@ACM@IEW[@ADDF?@CE@ECD@MGFECADGS?FCA@@CBQH@BABD?AFI@EEIF@J?KJHNMSDKTBGBABJdAKf@JPABOG}@?g@EE?W@O?Y@WAk@FU@DJCOFHG\\Dd@CJGXJb@?XHFOU[DC\\n@LD@DDKCAF??D@EADBMB@HEBB@GFKVSd@CS[EOCY@AEWAa@?S@I?}@HBBE?c@CIBCEOABECMsAWw@E_AMm@?MG]GKE]AOHo@g@_DEc@IWCe@UmAIBILFn@?HDHFj@DN@d@BZPn@Ah@Kd@CPWh@WB[T}@FQRCNJZTxAXrADb@GPa@TIJINEBBPDFAPGXKRCPC?@LSZ?HIHM?MIGKEWE@QZ_@OIYIJIB]a@KHIGO?]KKKMEMYKCCGEDGGCDGCQXAKIIGDECCBGCCBIEM@GCCFOEIDGFAHGBAEE??DIME@CECB[QA@GYULK?CD[BUCIJUIC@CGA@EAEJEOE@AJ@?FRMZBDWEOFABKASOF_CAOC@KC?BBECOHWDy@H@CADA@GC?HICE@?E@DB?CGAHCF@KEIOE?CDGBAEO?EEBFIHCCC@@IK@IEEB?NBIEDNACSCCHKSFLA@DF?EF[D?FWB@BGEMD@@MIE??DUICBCI?BC?MIO@GGE?[J@REFSGYHU@WNIISDIHE?@HAAER]TKACHG?AD@JEP?NGXKRFJI?KLYHSNADQ?CFSB@@CHED?DG@AFA??CQH_@DCE?FEHIF?EGHO@EJQJEEISM@QC?IE?ACDAEBICBCFBAF_@VGCAGCGGBKTKOG??@DCBDE^M?OHI?K\\ODUTSHIGI]NFf@CX@JDLKD\\?GJIN[\\W@HPXp@c@XKFHNJBL?JFHD?BDBJBA?FGLFC@HCLGHD?FJHBDTAHFNDB@EHFF?@E\\DBCDHBC@GBDJCAEHADDBJ",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": true,
    "visibility": "only_me",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      38.710739,
      -9.145257
    ],
    "end_latlng": [
      38.712589,
      -9.14633
    ],
    "average_speed": 1.064,
    "max_speed": 10.08,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 82.1,
    "elev_low": 6.3,
    "upload_id": 19756021731,
    "upload_id_str": "19756021731",
    "external_id": "37609CD4-E466-4D50-A729-7C20B18A3A5A-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 3,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Lunch Hike",
    "distance": 4930.4,
    "moving_time": 3679,
    "elapsed_time": 3778,
    "total_elevation_gain": 111.4,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18648374011,
    "id_str": "18648374011",
    "start_date": "2026-05-21T09:43:25Z",
    "start_date_local": "2026-05-21T11:43:25Z",
    "timezone": "(GMT+01:00) Europe/Paris",
    "utc_offset": 7200,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 2,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18648374011",
      "summary_polyline": "yzmfHkwmOYVW`@GROR[TCHw@z@IPQL]d@c@\\QHIJ[LY`@i@f@AFMHKZMV?HKXEVIHO@KFY`@G?ELGDMP?Fm@rAKZqA|CGFCCQDEH?FWr@DC?YIGG@OAKMmDiAkBs@UOG?_@Qi@MGEeA[SMKASMQIECEBEAk@QKIOCqAm@YGCFFZHhBJb@Hp@?xADhAKrAFf@m@aBw@eBmCoGv@dBvBhFR^FTJRHJHGDSD_AAa@G}BM_AE}@CACODqAF@@DJBD?BJF@@DhAh@RDb@RTDJFNBTHDFTDFDD?RHLBHFLBJFTFVLTD?BBHEDEZCr@Kl@Er@@ACF@d@@C?J?XOt@DPEhAGt@EN@XGNE^?BHDE@ICD@IL@BIPE`@E?Ol@Wz@AESbAAZGRCd@Yl@@?EB@@FIB@Kq@]eE[uBWu@k@iAu@uBKJJ@Xn@LTHXHNp@`BZbAl@hHDJDCHUJwAb@}ANq@N_@B?@UTo@Lo@LmCC@AEFKBy@Ja@AMCAAU?G@AAONcBDgADe@JFCE?@D@JBE@VFPLd@N\\PN@TLn@NRJJBCBHABBXFRHJJL?LGTYHCLHFNVLF@TOXH`@EP?BBPEL?PC^DTEN?RCJGb@g@HEDQK_@NKBGm@cC_@iACW[sAGKASHA\\WB@rAsARa@?EFONOB?H@^CLDFC?QNK@Ej@i@?EJKTMT[FQX]BMJIDAJOJETe@JGb@m@x@m@d@u@VKDIJE?K",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      48.407522,
      2.698745
    ],
    "end_latlng": [
      48.406481,
      2.69956
    ],
    "average_speed": 1.34,
    "max_speed": 4.77,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 134.6,
    "elev_low": 85.1,
    "upload_id": 19756021751,
    "upload_id_str": "19756021751",
    "external_id": "C033AC77-55E9-480C-83EA-3790466E302D-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Morning Hike",
    "distance": 3777.2,
    "moving_time": 4628,
    "elapsed_time": 6291,
    "total_elevation_gain": 107.3,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18547162350,
    "id_str": "18547162350",
    "start_date": "2026-05-17T16:43:07Z",
    "start_date_local": "2026-05-17T10:43:07Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 6,
    "comment_count": 1,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a18547162350",
      "summary_polyline": "kqutFvezdSCHBDAJAGA@@CABBHEb@Q`@KHGJCh@GRMRFJCBMAm@JKCOBIHODABAAMHODC?@ACEAB?E?BCACFS@?BYFOPQHABEB@CA@AA?@MRG?KE?E@@EKADJVCKCHGFSDM?OFQBc@AIB?@S?OJEAIHWHCDUAEDGBSEQKa@@CAQ@QGm@EI?[LM@IFQDSTo@hAQJI@BEE@[VILUTGLANAS@B?HCNYb@MDCDCA[JGFEE@BC?@@GF@@]`@B?C??C@B?AGHAAURg@JU@QC[H]AYHKX?A[PYh@QTg@d@Y|@YVAD@L?v@KLCH_@P_@?KDCASl@?KEZQf@CBe@JKLANPBC@NLn@^j@DJAJFr@HRJJRAPF?DJHLHPDZJLzABRDF?BCf@@PNNDFDLBHDDANFDCTB@BHAf@UN@DDHHd@XHNCFF@FFA?@AFDVXD@@FTZA@HDCH@AFBFJXXn@`@PXFDBJ\\XR^LLHP@FA@HR?CA@FXFx@DBB\\JXBRRf@C@BAFL@AHDA?CAFARAHEJQ@@C??CD??BAK@G@@C@?CA?B?A@@IAB@@AEB?VDRLLRZRTTJX?@F?PDJJFBDFFABMIo@?G@CXAPD\\@HAJ@C@R@PLFLFDLEHRD@FCDGJANSBOF??G@BEQHCDMDEB@BFBA?FFF@NN`@x@YH@DAA@@G@BA@DBL??CBDBAAAHB?CDBA@D??CABJH@KAAA@CMB@A?EKOm@@IDAC@?CGDA[?QDEAGFYDI@??IF[FD@KB?BZ@FDYBIB?BWBGHPBX?MHa@AUBQB@Pp@@a@FK@IFMFCN]@a@FYAGF_@@c@Hg@?UB_@AGBQCk@Jo@NWDSDoAAWCAB@?WZDLID]HQFCBG@_@BQFCH@NJNTD?@@@EAB?ADHNHF@`@VRFf@?VHNGA@F@DHNIJ?THLA?BA?H?BBN@FBDA",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.254727,
      -105.815615
    ],
    "end_latlng": [
      40.252291,
      -105.822188
    ],
    "average_speed": 0.816,
    "max_speed": 3.047,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 2674.9,
    "elev_low": 2556.7,
    "upload_id": 19653154908,
    "upload_id_str": "19653154908",
    "external_id": "33E25C6C-405B-423E-99C8-1C4ED0530603-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 4,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Lunch Hike",
    "distance": 6928.8,
    "moving_time": 6579,
    "elapsed_time": 8083,
    "total_elevation_gain": 117.5,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18534508127,
    "id_str": "18534508127",
    "start_date": "2026-05-16T18:33:13Z",
    "start_date_local": "2026-05-16T12:33:13Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 5,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a18534508127",
      "summary_polyline": "}xttFryzdSHYPyBP[PqBZ{B@UKIASRuBj@e@r@D^L`@HFEH}ADYPcCTwA?GIAJ_@JmAHc@d@cAj@aA^u@BPGGDCRo@JQt@}@PIDKT[J_@?SGe@?YHWv@g@PWZU^u@V[`@u@L[DYD?AKVLd@@XOz@_ApAi@FGJUV[|A{Bp@m@t@}@PYLa@`@{@P_ADs@L_@Z_@NYv@aAj@g@h@WDG?C\\SDOb@m@B?@QDOd@y@Rk@BAJa@?NB@?MAL@ABFEOGDH?@C?GJOACABEHBHb@g@h@e@r@UFS@YDa@Jk@@W\\c@f@iAlAuEVo@Z]j@Uj@C|D?l@KNGDIDQBi@FUJQzAw@LMJUJGJOPMZIDEt@Cb@SFI^EDBHERJ`@KRJNPVBJKDQC}@BCVEFQLIJWZQDUBC?KE??IG@@CIUCBGIK?UF?C@?GA?EAFC?CG@O@BBGNGJO@OHM?c@FCBKDABMHACD?D@EHHLDI?@EHBDBFLNFHJFRDB@NHIBLFB@G?F?CCA@BCB@B@C?B?ED@CEA@@DE@BAA??CDHCK?HAC@BC@BAAIDBEFCED@?GAF@?@@ADCEB@C@@ECBB@C@@G?D?EBBA?BAAA@@CB@GB?CGM?EINQBBIDCFE@AIS]YQMOMAMOE@GRC@?HC@ELIt@MPQFHPLBDIJAVNHNCBFZGN?HKBQL@GM\\MJAJEHM@@CMFCJFX@REPIHMDg@[SGKFO@OK{@PGF_@Lg@AcAf@[X@D[ZaAj@CDCVKMIBQpAMLo@HqADoAAWE{@Ri@\\W\\C@Sb@GV?HEBOn@GFCNIHIj@Yz@c@x@?JINUdACj@@NCF_@f@m@\\YXWLSVGNAJSXELOTC?CNO`@MP@BELMLMVo@f@EAQFc@\\QXg@f@Yb@KTYXGNOtAM\\CPOVc@hAQXGPUVOFGJ{@z@s@dAUh@o@\\CF@EA?CHOJMBg@\\GAIHKVQJIRMJc@NUASHKNGPQ\\e@r@{@|@CHWZSHe@f@CLFfAMb@U`@o@p@Q^WZUp@y@xAQT]|@a@zDOdA@HEZ?j@OnAIb@BP?NKVCPIH?HER@AED@DCJ@JHBE??HIR?BHH@JILGP@D@AARGd@DNAXEHEd@IFERKPOrAEPGz@",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.252346,
      -105.822214
    ],
    "end_latlng": [
      40.252351,
      -105.822235
    ],
    "average_speed": 1.053,
    "max_speed": 3.56,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 2587.7,
    "elev_low": 2557,
    "upload_id": 19640312281,
    "upload_id_str": "19640312281",
    "external_id": "C8D2CCB8-3245-44D9-8F33-244B5E5049BF-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Evening Hike",
    "distance": 40351.7,
    "moving_time": 3523,
    "elapsed_time": 3759,
    "total_elevation_gain": 53.8,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18485651242,
    "id_str": "18485651242",
    "start_date": "2026-05-13T01:23:00Z",
    "start_date_local": "2026-05-12T19:23:00Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 5,
    "comment_count": 2,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18485651242",
      "summary_polyline": "idyvFrsahTJrA\\t@G`@m@^eDjCL?S?Wh@q@TiAQ}@aASo@i@sCSyBm@Wk@AIOPq@OeB_@}@FUbAe@FFKeCx@[p@VZcBdAuATeBX[t@@DUX@FYNB?P@KTFDQOw@LWT@jCfBnAVtDMrFXnBc@`Ag@l@o@Zk@?OUIkAp@YIaBuHe@eAiAo@wIUwAPkEhBmAAwBkAmI{HoJyCgBWcC@cGnA_HvC_CxAuCzCqEjGuAbC{BfF}ClLmAlDaC`F_B~BuA~@aATeE?}@NmHfEgAtAmDrG_HfHsAhCmDzIgB|Cu@p@}@^iDVcAZeCzA{BzBcBjDgAlEgBrL{@xLc@fCyA|CeDfDeAbBsPre@qFvJsLla@qAnGeA|Pe@jDcA|EgDnNuHhT_Jz\\mB`F}DjIcAbBoGfIgVlf@{AjEg@hC[rCMtC@zCf@jG`Jb`@x@zAt@h@tBp@fAfAf@lBd@lEl@lBbA`BjHjIn@bA`@nAJbCu@pQDrCN~Aj@fCh@rAbKpO`AtBr@fCPbBHxCg@l]TbGhA|FzIrVf@xCn@jJv@bE~@hCt@tAvFzGbBfDjAdEtBnKrEdJlC|KhAbBzCxBz@~ALlAEnA[jAgBdDq@vB_@hCMrCPfGK`Ip@pKJnJ\\dE@vDLvAnAbGGnDd@pGu@lBgE|EaAfCLdA`@Pp@e@XoBl@CPd@Il@cD|GmA~CKjDL|Il@jCzBtEpTt]`AvDt@zHh@~Cl@~AhCpEbCpDvB|AzAVdECbAn@lApC^X~D[nA\\p@d@|@rA^bALlA@hD^bCrDpHb@jANvANbGObAa@x@mAj@qHSaAt@U`ANjB`BbFJnD\\z@nAtAV|@HnGs@lNh@|EI`AeApCQdA?nEi@nH{AdH_BfEGdAP`A`CnC`BhErDvDrBdDz@pB`BxFtEtJVrAb@dGhDrGh@tBb@zEJnFAvXoBtLs@hIGdFOv@qDjAoBfBcOdZeCpDw[rYqBbAyB\\sPo@aBF_Cr@wBbBiAhBs@`C{DvX}AfEsC`G]dBF~Al@~An@l@rDdBtAtAt@fAnBjF`AjFPdCHrEu@l`@@|d@R~Hv@xHtP~dAn@fFZlFJnFHzc@bB~g@RlMHxtAa@nKsG`oA{@zJaBxGyH|NeB|Fs@zEm@vKg@fFeC|Nw@pBo@z@mClB_B\\cB@_JsBaFu@mh@_C{e@iEw@Bc@VSV[nAA~DvB|[J\\h@NzWCv@Yf@{@",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.603178,
      -111.584908
    ],
    "end_latlng": [
      40.648096,
      -111.907993
    ],
    "average_speed": 11.454,
    "max_speed": 35.08,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 2671,
    "elev_low": 1308.5,
    "upload_id": 19590983696,
    "upload_id_str": "19590983696",
    "external_id": "068FFDFB-4AD2-4F26-8D3A-D28C8F9CC083-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Morning Hike",
    "distance": 3260.1,
    "moving_time": 2699,
    "elapsed_time": 3042,
    "total_elevation_gain": 2.2,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18485253931,
    "id_str": "18485253931",
    "start_date": "2026-05-12T15:33:58Z",
    "start_date_local": "2026-05-12T09:33:58Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 5,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18485253931",
      "summary_polyline": "g_awFrubjTt@Db@Eh@?v@FRHN?PKX_@`@_@PM\\ERDtAf@`@H^Af@QTER@d@FCDHEXJTVLJRDVADD\\@@DDCRAAEHCB?NCHDxAy@D?d@OD?BBLAfADz@Lh@X`@JBDBR?ZAR@f@ADAA@F?CAB@CJHX@XH`@Zn@Z?@C@CCD@AC?BF?NFEDBEDDx@PXNZJx@Nj@Nh@^XZ`@Zn@\\b@\\NFjAbABADFLDFHXPNDb@TTD`AAl@KJ@HI?@EAE@CH@HCF?@D??HGGDUCGMDYB]HM?GC]B]IKMi@S_@W}@u@w@e@c@_@YMEIABe@e@OKSUWM@C]IOAKE{@OcBs@_@Ka@Q_@[_@OK?@?ACIBEAGICS@uAAMQI_@IWSOEY?[Ie@Eu@Aw@Tu@b@QLKDQIE@?AK@UWCGCBE?EBGEBDCBSGBFGHBJc@?QKGMD_AIc@We@a@e@i@Ys@[iAQe@Qk@Kk@Ck@F@BI@OJBDEDODAC?FEGBBABSLGBOAa@SE?{@SOAi@Ls@@uA\\",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.644197,
      -111.921792
    ],
    "end_latlng": [
      40.644356,
      -111.921645
    ],
    "average_speed": 1.208,
    "max_speed": 3.56,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 1303.7,
    "elev_low": 1301.3,
    "upload_id": 19590582302,
    "upload_id_str": "19590582302",
    "external_id": "F93AD9F2-15C6-42A8-B8A2-3F2132147C9E-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Morning Hike",
    "distance": 5266.4,
    "moving_time": 4250,
    "elapsed_time": 4997,
    "total_elevation_gain": 7.7,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18485253995,
    "id_str": "18485253995",
    "start_date": "2026-05-10T15:35:24Z",
    "start_date_local": "2026-05-10T09:35:24Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 6,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18485253995",
      "summary_polyline": "exawFf`cjTa@Zo@~@e@`BYh@u@~@MDWNG?AD}@n@[JW?MCe@Qu@EMBUN@AE?K@ABQAGFIpACFGB[@u@E]EWGQIMOU]QgAK]II]MIGW]e@_Ag@q@eAs@QQDC?@CC@DC?aAg@{@g@Y?UGk@@MFMAQHIEO?CAAKMSIMICOGmAOk@Ue@DOAuAe@EEy@Ys@MKOQKk@Ku@Wu@Gu@a@wAi@_AKy@We@Ky@]C??FGK{@u@CEYYQ_@MUM]S_@AKA?@QAGGG[KOM_@y@IM[u@i@y@q@gA?@QQ]WIEA@CC_@OOMIM_AyBUa@SU]Yy@aAGUEm@?]BWAWIY@WIg@?}@AOCA@EDGD?DIE?B?@BCCBBAC?IC@KEGICMEm@?EC??@DC?QES@CAD@ACADAGDQw@AS?SBIAC@ILLDz@RhBJn@d@v@Pd@T^Pf@BTFbAH|@HXAHCCQAAKAAGBCJKBGT?ZHNh@d@RZVf@j@tAVd@LJd@P`@Tf@j@~@|AnAjCn@^Hn@JTJ\\Zh@Z\\FB@Dx@p@TL|@ZbAXd@Jj@Dn@Zt@Rd@\\TD`@Bj@Rl@HNHBFLNLHLDFFfA`@`@HJFp@N\\BJD\\DZClANPFb@`@?FDFFBWJt@EFB@IFBPGt@?@I@FH@T?C?BECDLHXJDDZHRNZLd@b@n@`@VTTX~@`BHHl@^FPHj@Lj@DHPRLHE?@ARJb@FHB^BABACABCAlDCDEBBZBhA@rAURKj@k@b@o@Xw@\\wALOL[ZoAb@s@v@{@",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.644705,
      -111.922211
    ],
    "end_latlng": [
      40.644531,
      -111.922022
    ],
    "average_speed": 1.239,
    "max_speed": 5.7,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 1301.9,
    "elev_low": 1296.8,
    "upload_id": 19590582308,
    "upload_id_str": "19590582308",
    "external_id": "28698499-74C7-41FD-952B-DEBD41E60A16-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Morning Hike",
    "distance": 2118.7,
    "moving_time": 2261,
    "elapsed_time": 7470,
    "total_elevation_gain": 2.8,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18442862960,
    "id_str": "18442862960",
    "start_date": "2026-05-09T16:21:56Z",
    "start_date_local": "2026-05-09T10:21:56Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 5,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18442862960",
      "summary_polyline": "irtwFvpyiTB?HDNG?@GI@KEA?@BCCBH@GABBABL?BBN?HEDKIQ?K@BABCCBACHFAC?@EDECBAEEC@EB?@AF??B@?B?CB@I@L?GDAIB?HBFHLNSAAEDBA?GABB?AAA@B@?IDDCC?J?E@B@AACBGC@AC?BBA@BAA?C@DACABBCABDBGC@K@BABDFCFBAAGGLE@BE@FE@IJQN@E?BODOPe@FA@FJDGB?A@B@?E?B@ECDDA?CDBCBBFSM@GDEF?VGVMPU@GBCNA?GBDA@?AC?D@DGGB?A@BEGBHCCA@?EA@D@@CAAABDCC?BHAKEHALCAEH?AC@?@DB?RD@?@B?C@CAJCBEL?FCAGHMBC@CB??ME?CEDKAOEC?@I@AAA@?C?BA?@CAGGCEDCEA?FBCF?EC@ECG@QVQU?UCAB?AABA?BG@@B_@BCFI?ID]DEDKADCA?A@HEH@AJ@?EDAEC??EC@AGBAB@IBHI?B@@BG@BMAAHCBCAFIDBD?BLDDE@DA?DGA@?@L@CEFHVCGCBBGCFA@AABC?@AJC@@?AC",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.743162,
      -111.876235
    ],
    "end_latlng": [
      40.743244,
      -111.876223
    ],
    "average_speed": 0.937,
    "max_speed": 7.2,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 1300.1,
    "elev_low": 1296.4,
    "upload_id": 19547770258,
    "upload_id_str": "19547770258",
    "external_id": "5D5B5388-21DA-48A0-958C-7DEA53DF0237-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Afternoon Hike",
    "distance": 4241.6,
    "moving_time": 4304,
    "elapsed_time": 5486,
    "total_elevation_gain": 124,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18431954311,
    "id_str": "18431954311",
    "start_date": "2026-05-08T23:17:47Z",
    "start_date_local": "2026-05-08T17:17:47Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 5,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18431954311",
      "summary_polyline": "uasvFtteiT@GM_@B]A[EBCJGDGEAI@EAe@DM?SDI?a@@IAIDUAQDc@AGBWD@GM?QI[E]K_@ASEEYy@Ca@M_ABy@PiAHWh@kABANk@BCLq@HiAA_AO{BCu@@k@Ec@E}@AEGi@EMAU@A@KCW?Q@??WBWAO@CABAC?C@@BQ?q@DYA_@BaABK?QHQ?KBALq@Hq@Gq@CE@CCECUDcAAGG@B?CBFQDwALa@NoAASHgACUDa@CG@GEG?KA??GA@FIBMEi@E[Ae@Wi@@CAKCG@GMSAGBGEO@OEWGO?MADE[Ac@EOGB?EAAC@@IM_@MQGU?HDF@CEC@IAAGBD?A@@A@F?GBAAACBB@E@FBEC?GEB@E?B?QEC?EDQCGDQAEFOJm@LsADK@g@CYBM?y@FBGGDu@Fa@HICC@GGFB@?BEA?E@@C?@A@B?CBB?C@@A@B@LOE@FFKIP]JgAAK?SCIBCAQDEDq@CC@e@GK@OAI?IDSBA?MRi@LOFUA[BYEMAi@EG?EBa@C@KI?B?GC@?KDC@FBHCICB?CHBAAICGBEEFFDGKF?QGIA@CEDG?DC?HB?VJ?EE@GB@ADC@AF@EDJHBJZFl@AzAG^KHKNS~@?VBHDx@GXBD?ZGT@r@CH@NI^O\\OPCRGzB@rAKbAWvAGn@BZLd@NZFDHLJZH`AH`@?JJp@^`BBh@Fb@En@BF?RCVAfAMlBQnA?j@Bh@AJGD?j@H`@@d@DJ?Ti@rCA`COhD^hFAf@DfALzA?jAE`@EJIn@Wv@_@z@Sp@Iz@GVAj@@`@N`Aj@lBBRJn@Dl@ItA?x@OxA?DD@KAB?A\\",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.571879,
      -111.774655
    ],
    "end_latlng": [
      40.571831,
      -111.774521
    ],
    "average_speed": 0.986,
    "max_speed": 2.36,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 1770.8,
    "elev_low": 1648.4,
    "upload_id": 19536729666,
    "upload_id_str": "19536729666",
    "external_id": "569071A1-9F22-4BEA-A702-49ED851980BA-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {
      "id": 135081398,
      "id_str": "135081398",
      "resource_state": 1
    },
    "name": "Evening Hike",
    "distance": 2114.9,
    "moving_time": 1874,
    "elapsed_time": 2118,
    "total_elevation_gain": 76.2,
    "type": "Hike",
    "sport_type": "Hike",
    "device_name": "Strava App",
    "id": 18326299352,
    "id_str": "18326299352",
    "start_date": "2026-05-01T01:01:37Z",
    "start_date_local": "2026-04-30T19:01:37Z",
    "timezone": "(GMT-07:00) America/Denver",
    "utc_offset": -21600,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 0,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a18326299352",
      "summary_polyline": "ie{vFtefiTDICAB?AC?@BCEMFDAGBACADBCEBQ@?BL@CG??KDAEABCCC@AC@@AACFE@@FOE@BCAF?DDDALAM@B@KIE@CF?G@DFAB?CB@CFBE?DC@COAJABFGIH?FDPEFGE@HAHCEEAD@AIBLIRIBF?@FFFGJB@ELB@?BKMCD@D?LC@@A@B@A@BHD?LBFEGGP?L@JBDENID@DCHIHCHEp@EJADCDCTM\\BBA?AJEBAD?P@DEDCNBHAPC@?JA?CF@ADDAPA@BFAP@LAE?BBCCD@??BYVE@?J?CGE@HG?AHEGI@MAFTPF?LAAAHB@AFBCCGBB@RCFAAFR@?ABDPEBBH?CB?GBGEGDCCMHKGCBBZRJC@MLBHDBC??DFF?R?CEDDRB?GF@FI\\@@Oj@AFBBMP?FEP@?BRCXBCE\\BPCXDJCHFN@RAJF^B@A@?VD`@FL@\\J^@r@ALDZAPBVFZ?d@DVAHFT@ZAVDZELA`@MPGTGDA\\STADB?Of@ALCDAV@BB?DILs@@TH^DDFPLFPd@F^HJTPZJ`@GV@LDFFL`@Zn@NPF@ZP",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": true,
    "visibility": "only_me",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [
      40.61333,
      -111.777929
    ],
    "end_latlng": [
      40.610281,
      -111.788191
    ],
    "average_speed": 1.129,
    "max_speed": 3.08,
    "has_heartrate": false,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": false,
    "elev_high": 1785.8,
    "elev_low": 1598.4,
    "upload_id": 19429991089,
    "upload_id_str": "19429991089",
    "external_id": "E93EF174-46B7-45AA-A600-F5684C3EB9A7-activity.fit",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  }
];